### ISSUE TITLE
Error while using aiohttp 0.20.0

### ISSUE THREAD

**Issue by sayoun** [mardiros/aioxmlrpc#3]
Hello,

I used the example from the readme and it doesn't work with aiohttp in version 0.20.0 (debian jessie version)

It seems related to this http://stackoverflow.com/a/34972564

The full traceback:

```
Unexpected error
Traceback (most recent call last):
  File "/home/sayoun/.virtualenvs/testtest/lib/python3.4/site-packages/aioxmlrpc/client.py", line 72, in request
    body = yield from response.read_and_close()
AttributeError: 'ClientResponse' object has no attribute 'read_and_close'
Traceback (most recent call last):
  File "/home/sayoun/.virtualenvs/testtest/lib/python3.4/site-packages/aioxmlrpc/client.py", line 72, in request
    body = yield from response.read_and_close()
AttributeError: 'ClientResponse' object has no attribute 'read_and_close'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "test.py", line 13, in <module>
    loop.run_until_complete(print_gandi_api_version())
  File "/usr/lib/python3.4/asyncio/base_events.py", line 337, in run_until_complete
    return future.result()
  File "/usr/lib/python3.4/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.4/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "test.py", line 8, in print_gandi_api_version
    result = yield from api.version.info()
  File "/home/sayoun/.virtualenvs/testtest/lib/python3.4/site-packages/aioxmlrpc/client.py", line 37, in __call__
    ret = yield from self.__send(self.__name, args)
  File "/home/sayoun/.virtualenvs/testtest/lib/python3.4/site-packages/aioxmlrpc/client.py", line 124, in __request
    verbose=self.__verbose
  File "/home/sayoun/.virtualenvs/testtest/lib/python3.4/site-packages/aioxmlrpc/client.py", line 81, in request
    str(exc), response.headers)
xmlrpc.client.ProtocolError: <ProtocolError for https://rpc.gandi.net/xmlrpc/: 200 'ClientResponse' object has no attribute 'read_and_close'>
Unclosed response
client_response: <ClientResponse(https://rpc.gandi.net/xmlrpc/) [200 OK]>
<CIMultiDictProxy('DATE': 'Wed, 25 May 2016 20:03:03 GMT', 'SERVER': 'Apache/2.2.16 (Debian) mod_ssl/2.2.16 OpenSSL/0.9.8o mod_wsgi/3.3 Python/2.6.6', 'VARY': 'Accept-Encoding', 'CONTENT-ENCODING': 'gzip', 'CONTENT-LENGTH': '141', 'CONNECTION': 'close', 'CONTENT-TYPE': 'text/xml; charset=utf-8')>

```

**Comment by ludovic-gasc** [comment]
You can close this issue, it has fixed with #4
